// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// nllfun_cpp
double nllfun_cpp(const Eigen::VectorXd& obs_E, const Eigen::MatrixXd& obs_V, const Eigen::VectorXd& pred_E, const Eigen::MatrixXd& pred_V, double n);
RcppExport SEXP _admr_nllfun_cpp(SEXP obs_ESEXP, SEXP obs_VSEXP, SEXP pred_ESEXP, SEXP pred_VSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type obs_E(obs_ESEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type obs_V(obs_VSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type pred_E(pred_ESEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type pred_V(pred_VSEXP);
    Rcpp::traits::input_parameter< double >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nllfun_cpp(obs_E, obs_V, pred_E, pred_V, n));
    return rcpp_result_gen;
END_RCPP
}
// nllfun_var_cpp
double nllfun_var_cpp(const Eigen::VectorXd& obs_mean, const Eigen::VectorXd& obs_var, const Eigen::VectorXd& pred_mean, const Eigen::VectorXd& pred_var, int n);
RcppExport SEXP _admr_nllfun_var_cpp(SEXP obs_meanSEXP, SEXP obs_varSEXP, SEXP pred_meanSEXP, SEXP pred_varSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type obs_mean(obs_meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type obs_var(obs_varSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type pred_mean(pred_meanSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type pred_var(pred_varSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(nllfun_var_cpp(obs_mean, obs_var, pred_mean, pred_var, n));
    return rcpp_result_gen;
END_RCPP
}
// logdens2wt_cpp
Eigen::VectorXd logdens2wt_cpp(const Eigen::VectorXd& x);
RcppExport SEXP _admr_logdens2wt_cpp(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(logdens2wt_cpp(x));
    return rcpp_result_gen;
END_RCPP
}
// compute_variance_cpp
Eigen::MatrixXd compute_variance_cpp(const Eigen::MatrixXd& d_f_d_bi, const Eigen::MatrixXd& Omega);
RcppExport SEXP _admr_compute_variance_cpp(SEXP d_f_d_biSEXP, SEXP OmegaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type d_f_d_bi(d_f_d_biSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Omega(OmegaSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_variance_cpp(d_f_d_bi, Omega));
    return rcpp_result_gen;
END_RCPP
}
// gen_bi2_cpp
Eigen::MatrixXd gen_bi2_cpp(const Eigen::MatrixXd& Omega, const Eigen::MatrixXd& biseq);
RcppExport SEXP _admr_gen_bi2_cpp(SEXP OmegaSEXP, SEXP biseqSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type biseq(biseqSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_bi2_cpp(Omega, biseq));
    return rcpp_result_gen;
END_RCPP
}
// meancov_cpp
List meancov_cpp(const Eigen::MatrixXd& M, const Eigen::VectorXd& w);
RcppExport SEXP _admr_meancov_cpp(SEXP MSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type M(MSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(meancov_cpp(M, w));
    return rcpp_result_gen;
END_RCPP
}
// gen_bi_batch_cpp
Eigen::MatrixXd gen_bi_batch_cpp(const Eigen::MatrixXd& Omega, int n_samples);
RcppExport SEXP _admr_gen_bi_batch_cpp(SEXP OmegaSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(gen_bi_batch_cpp(Omega, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// jacobiann_vec_fast_cpp
NumericMatrix jacobiann_vec_fast_cpp(Function f, NumericVector bi, double eps);
RcppExport SEXP _admr_jacobiann_vec_fast_cpp(SEXP fSEXP, SEXP biSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bi(biSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(jacobiann_vec_fast_cpp(f, bi, eps));
    return rcpp_result_gen;
END_RCPP
}
// MCapprEV_cpp
List MCapprEV_cpp(NumericMatrix m, NumericVector logwt);
RcppExport SEXP _admr_MCapprEV_cpp(SEXP mSEXP, SEXP logwtSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type m(mSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type logwt(logwtSEXP);
    rcpp_result_gen = Rcpp::wrap(MCapprEV_cpp(m, logwt));
    return rcpp_result_gen;
END_RCPP
}
// samplogdensfun_cpp
Eigen::VectorXd samplogdensfun_cpp(const Eigen::MatrixXd& bi, const Eigen::MatrixXd& Omega, double omega_expansion);
RcppExport SEXP _admr_samplogdensfun_cpp(SEXP biSEXP, SEXP OmegaSEXP, SEXP omega_expansionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type bi(biSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type Omega(OmegaSEXP);
    Rcpp::traits::input_parameter< double >::type omega_expansion(omega_expansionSEXP);
    rcpp_result_gen = Rcpp::wrap(samplogdensfun_cpp(bi, Omega, omega_expansion));
    return rcpp_result_gen;
END_RCPP
}
// g_iter_generic_cpp
NumericMatrix g_iter_generic_cpp(Function gfun, NumericVector beta, NumericMatrix bi, Nullable<NumericVector> ai);
RcppExport SEXP _admr_g_iter_generic_cpp(SEXP gfunSEXP, SEXP betaSEXP, SEXP biSEXP, SEXP aiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Function >::type gfun(gfunSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type bi(biSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type ai(aiSEXP);
    rcpp_result_gen = Rcpp::wrap(g_iter_generic_cpp(gfun, beta, bi, ai));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_admr_nllfun_cpp", (DL_FUNC) &_admr_nllfun_cpp, 5},
    {"_admr_nllfun_var_cpp", (DL_FUNC) &_admr_nllfun_var_cpp, 5},
    {"_admr_logdens2wt_cpp", (DL_FUNC) &_admr_logdens2wt_cpp, 1},
    {"_admr_compute_variance_cpp", (DL_FUNC) &_admr_compute_variance_cpp, 2},
    {"_admr_gen_bi2_cpp", (DL_FUNC) &_admr_gen_bi2_cpp, 2},
    {"_admr_meancov_cpp", (DL_FUNC) &_admr_meancov_cpp, 2},
    {"_admr_gen_bi_batch_cpp", (DL_FUNC) &_admr_gen_bi_batch_cpp, 2},
    {"_admr_jacobiann_vec_fast_cpp", (DL_FUNC) &_admr_jacobiann_vec_fast_cpp, 3},
    {"_admr_MCapprEV_cpp", (DL_FUNC) &_admr_MCapprEV_cpp, 2},
    {"_admr_samplogdensfun_cpp", (DL_FUNC) &_admr_samplogdensfun_cpp, 3},
    {"_admr_g_iter_generic_cpp", (DL_FUNC) &_admr_g_iter_generic_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_admr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
