#' Generate a simulated dataset
#'
#' @description
#' `gendataset` generates a simulated dataset based on the model structure and random effects
#' specified in the options. The function can generate data in either raw format or nlmixr format,
#' with optional residual error.
#'
#' @param opts A list of model options generated by `genopts()`. Contains settings for the model,
#'             including the prediction function, time points, parameter structure, and simulation
#'             settings.
#' @param seed Random seed for reproducibility. Default is 1.
#' @param reserr Logical indicating whether to add residual error to the simulated data.
#'              Default is TRUE.
#' @param nlmixrform Logical indicating whether to return the data in nlmixr format.
#'                   If TRUE, returns a data frame with columns: dv, time, id, amt, evid, cmt.
#'                   If FALSE, returns a matrix of simulated observations.
#'                   Default is FALSE.
#'
#' @returns If `nlmixrform` is FALSE, returns a matrix of simulated observations with dimensions
#'          `nsim` x `length(time)`. If `nlmixrform` is TRUE, returns a data frame in nlmixr
#'          format with columns:
#'          \itemize{
#'            \item `dv`: Observed value
#'            \item `time`: Observation time
#'            \item `id`: Subject ID
#'            \item `amt`: Dose amount (NA for observations)
#'            \item `evid`: Event type (101 for dosing, 0 for observation)
#'            \item `cmt`: Compartment number (1 for depot, 2 for central)
#'          }
#'
#' @details
#' The function generates simulated data by:
#' \itemize{
#'   \item Generating random effects from the specified distribution
#'   \item Computing individual parameters using the transformation function
#'   \item Simulating observations using the prediction function
#'   \item Adding residual error if requested
#'   \item Formatting the output according to the specified format
#' }
#'
#' The residual error can be either proportional (Sigma_prop) or additive (Sigma_add), or both.
#' The function uses the random number generator seed to ensure reproducibility.
#'
#' @examples
#' # Create model options
#' opts <- genopts(
#'   f = predder,
#'   time = c(.1, .25, .5, 1, 2, 3, 5, 8, 12),
#'   p = list(
#'     beta = c(cl = 5, v1 = 10, v2 = 30, q = 10, ka = 1),
#'     Omega = matrix(c(0.09, 0, 0, 0, 0,
#'                     0, 0.09, 0, 0, 0,
#'                     0, 0, 0.09, 0, 0,
#'                     0, 0, 0, 0.09, 0,
#'                     0, 0, 0, 0, 0.09), nrow = 5, ncol = 5),
#'     Sigma_prop = 0.04
#'   ),
#'   nsim = 2500,
#'   n = 500
#' )
#'
#' # Generate dataset in raw format
#' data_raw <- gendataset(opts)
#'
#' # Generate dataset in nlmixr format
#' data_nlmixr <- gendataset(opts, nlmixrform = TRUE)
#'
#' @export
gendataset <- function(opts, seed = 1, reserr = TRUE, nlmixrform = FALSE) {
  set.seed(seed)
  bi <- gen_bi(opts,FALSE)
  nsimobs <- length(opts$time)*opts$nsim
  theta_i <- g_iter(opts,bi)
  res <- opts$f(opts$time,theta_i)
  if (!reserr) return(res)
  if (!is.null(opts$p$Sigma_prop))
    res <- res*(1+rnorm(nsimobs,sd=sqrt(opts$p$Sigma_prop)))
  if (!is.null(opts$p$Sigma_add))
    res <- res+rnorm(nsimobs,sd=sqrt(opts$p$Sigma_add))
  if (!nlmixrform) {
    return(res)
  } else {
    tibble(dv=c(t(cbind(NA,res))),time=rep(c(0,opts$time),times=opts$nsim),
           id=rep(seq_len(opts$nsim),each=1+length(opts$time)),
           amt=rep(c(100,rep(NA,length(opts$time))),opts$nsim),
           evid=101*as.integer(!is.na(.data$amt)),
           cmt=ifelse(is.na(.data$amt),2,1))
  }
}
