# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

nllfun_cpp <- function(obs_E, obs_V, pred_E, pred_V, n = 1L) {
    .Call(`_admr_nllfun_cpp`, obs_E, obs_V, pred_E, pred_V, n)
}

nllfun_var_cpp <- function(obs_mean, obs_var, pred_mean, pred_var, n = 1L) {
    .Call(`_admr_nllfun_var_cpp`, obs_mean, obs_var, pred_mean, pred_var, n)
}

logdens2wt_cpp <- function(x) {
    .Call(`_admr_logdens2wt_cpp`, x)
}

compute_variance_cpp <- function(d_f_d_bi, Omega) {
    .Call(`_admr_compute_variance_cpp`, d_f_d_bi, Omega)
}

gen_bi2_cpp <- function(Omega, biseq) {
    .Call(`_admr_gen_bi2_cpp`, Omega, biseq)
}

meancov_cpp <- function(M, w) {
    .Call(`_admr_meancov_cpp`, M, w)
}

gen_bi_batch_cpp <- function(Omega, n_samples) {
    .Call(`_admr_gen_bi_batch_cpp`, Omega, n_samples)
}

jacobiann_vec_fast_cpp <- function(f, bi, eps = 1e-8) {
    .Call(`_admr_jacobiann_vec_fast_cpp`, f, bi, eps)
}

MCapprEV_cpp <- function(m, logwt) {
    .Call(`_admr_MCapprEV_cpp`, m, logwt)
}

samplogdensfun_cpp <- function(bi, Omega, omega_expansion) {
    .Call(`_admr_samplogdensfun_cpp`, bi, Omega, omega_expansion)
}

g_iter_generic_cpp <- function(gfun, beta, bi, ai = NULL) {
    .Call(`_admr_g_iter_generic_cpp`, gfun, beta, bi, ai)
}

